export { default as Header } from "./Header";
export { default as Modal } from "./Modal";
export { default as Tags } from "../styleUpdate/Tags";
export { default as Items } from "../styleUpdate/Items";
export { default as PageMy } from "./PageMy";
export { default as PageStyle } from "./PageStyle";
export { default as PageCody } from "./PageCody";
export { default as PageSize } from "./PageSize";
export { default as PagePayment } from "./PagePayment";
